### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [vasu-1/CalcHub#313]
👋 Hi @vasu-1 ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Collaborate` repo. This means that you want to invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/vasu-1/CalcHub/issues/314
- [x] https://github.com/vasu-1/CalcHub/issues/315
- [x] https://github.com/vasu-1/CalcHub/issues/316
- [x] https://github.com/vasu-1/CalcHub/issues/317

**Comment by ericdrosado** [comment]
Congratulations on completing all of the issues @vasu-1 ! 🎉 

Next week I will contact you with next steps. 

For now, I would recommend finding some help to tackle all of the issues you have in your repo. Your repo is very popular! 😅

**Comment by ericdrosado** [comment]
> So, what is the process for doing the same? What information we must provide in our application? 

GitHub partners with Major League Hacking for Hackathon support. 

To organize a hackathon with support from GitHub, simply become an MLH member (it's free!):

[Join the MLH Hackathon Season](https://mlh.io/event-membership)

GitHub can provide up to $1,000 through the GitHub Hackathon Grant.

Major League Hacking provides GitHub collateral and swag to all MLH Member Events, and runs our #MyOctocat drawing contest at all hackathons.

If you have further questions please inquire with MLH:

[Contact Us](https://mlh.io/contact)

**Comment by vasu-1** [comment]
Hii @ericdrosado!
Are there any updates?

**Comment by ericdrosado** [comment]
👋 Hey @vasu-1 ! An email has been sent 😄

**Comment by vasu-1** [comment]
> 👋 Hey @vasu-1 ! An email has been sent 😄

Yep! Done.

**Comment by ericdrosado** [comment]
It's been a pleasure to work with you @vasu-1 ! I'll go ahead and close this issue.
